version: '3.8'

services:
  couchbase:
    image: couchbase/server:community
    container_name: couchbase-mpg
    restart: always
    ports:
      - "8091-8096:8091-8096"
      - "11210:11210"
    env_file:
      - .env
    volumes:
      - couchbase_data:/opt/couchbase/var
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    entrypoint: [ "/bin/bash", "/docker-entrypoint-initdb.d/init.sh" ]

  nodejs:
    image: node:18
    container_name: mpg-node
    restart: always
    depends_on:
      - couchbase
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./server:/app
    working_dir: /app
    command: bash -c "npm install && npm run start"

volumes:
  couchbase_data:
